### ISSUE TITLE
这么好的模块，啥时候能更新一下？

### ISSUE THREAD

**Issue by yksos518** [hujiayucc/NoTask#3]
作者大大，能不能更新下这个模块啊，8.04x以上微信，打开就会有一段白屏时间，8.0.3x正常

**Comment by hujiayucc** [comment]
请提供相关日志信息到此邮箱：[hujiayucc@qq.com](mailto:hujiayucc@qq.com)

**Comment by hujiayucc** [comment]
在1.1版本中此问题已修复
